version: "3.7"

services: 
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: rentx
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    working_dir: /usr/app
    network_mode: host


volumes: 
  pgdata: 
    driver: local